### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [Tercioo/Details-Damage-Meter#309]
Installing Details! for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/170102215-27807426-7da1-4da0-b738-30f8a83d1960.png)

The URL used for installing for the above image was: https://github.com/Tercioo/Details-Damage-Meter

Consult the guide posted by WoWUp which may correct the issue: https://wowup.io/guide/wowup/curseforge-migration

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing.

**Comment by Flamanis** [comment]
Terciob is looking into other places besides curseforge. Patience is a virtue.

**Comment by clicketz** [comment]
In the meantime, releases could just be packaged on github.

This is already done properly and works with WoWUP/cursebreaker for terciob's other addon `Plater Nameplates`, so I'm a bit confused on the disconnect for details

**Comment by byeuji** [comment]
Adding my wish to support even the minor modifications to the github for manual install (via URL in Wowup). Huge fan of this addon and would like to continue using it! Thank you for your hard work, Tercio!

**Comment by BlazeDale** [comment]
Looking to use this via WoWUp as well.

**Comment by b4shx0r** [comment]
yes thankks for wowup support in future :)

**Comment by abaskett3** [comment]
Adding my support for github releases and WoWUp support. Thanks again to Terciob and team for their hard work :)

**Comment by p3ak** [comment]
Pushing - And thanks for your hard work.

**Comment by Natherul** [comment]
Any news on this?

**Comment by YoanKECH** [comment]
+1

**Comment by Rudi9719** [comment]
Checking in on this, since it would make updates quicker and easier on the developer if users were grabbing from GitHub directly instead of a platform the dev needs to manually update. Not to mention, it works in the dev's other repos?

**Comment by Squiry** [comment]
>  Have you gone through this? If the commit is what it states to be then it would be the solution

Don't think that `+19,558/−12,196` pr is someone will approve.

**Comment by Flamanis** [comment]
> > Have you gone through this? If the commit is what it states to be then it would be the solution
> 
> Don't think that `+19,558/−12,196` pr is someone will approve.

I'd rather not have to fix all of the bugs he's reverted in that PR. Terciob is still looking into other hosts. They do have a life and more than likely this isn't a massive priority. You're able to download the addon through curseforge. Even if you hate overwolf for their past bs, you don't have to deal with them if you manually install.

**Comment by himea-saito** [comment]
Adding my wish here as well. I refuse to use CurseForge after their API change, and I'm fine with not using any addon that continues to select only them as a distribution platform.

**Comment by Natherul** [comment]
Agreed. Until fixed Im not updating skada and I will use something else. Not even going to the curseforge site.

**Comment by JustusW** [comment]
I've forked this repository into one that can be used in WoWUp. (https://github.com/JustusW/Details-Damage-Meter) There are certain issues with the packaging (I'm using BigWigsMod to package automatically), for example some language strings don't work correclty, but for the most part it works.
It's set up so it will grab this repository daily and publish it again.

**Comment by LukasDahl** [comment]
> I've forked this repository into one that can be used in WoWUp. (https://github.com/JustusW/Details-Damage-Meter) There are certain issues with the packaging (I'm using BigWigsMod to package automatically), for example some language strings don't work correclty, but for the most part it works. It's set up so it will grab this repository daily and publish it again.

Have you gotten permission to do this from the author? I'm pretty sure this isn't permissible under the "All Rights Reserved" license that Details is licensed under. Usually redistribution is not allowed unless explicitly stated.

**Comment by LukasDahl** [comment]
> > > I've forked this repository into one that can be used in WoWUp. (https://github.com/JustusW/Details-Damage-Meter) There are certain issues with the packaging (I'm using BigWigsMod to package automatically), for example some language strings don't work correclty, but for the most part it works. It's set up so it will grab this repository daily and publish it again.
> > 
> > 
> > Have you gotten permission to do this from the author? I'm pretty sure this isn't permissible under the "All Rights Reserved" license that Details is licensed under. Usually redistribution is not allowed unless explicitly stated.
> 
> Im no lawyer but there is no license set in the repo nor a LICENSE file in the repo. If they dont want it to happen they should do it themselves or not host it openly on github.

Software licenses do no require the license to be stated in the source code. It is stated on CurseForge. Just because you don't agree with a dev (or think they are too slow to implement a change) does not mean you get privileges to violate the license.

**Comment by Natherul** [comment]
Its moot to argue but pointing at another site and its license there is shaky at best considering that this github repo does not link directly to curseforge sure we all know its there. But even so the link you provided explicitly also state the point of a fork which is exactly what JustusW did. I mean Im sure he would take it down if requested (idk but I assume so), but then imho tericoo should have set a license here stating he does not want forks or not have it all public

**Comment by LukasDahl** [comment]
I completely agree that Tericoo should put a license on here. I'm just pointing out that redistributing the code in zip files is probably not allowed in case JustusW didn't know.

**Comment by Flamanis** [comment]
The only distasteful part of the conversation was you calling wow addon development "A toxic waste dump".

The only GPL software in the project is LibCompress. There is an LGPL library used, I'm too lazy to find which one. But doesn't matter because of LibCompress.

> As a matter of fact since he built his code on GPL software he does not even technically own the code.

This is actually against GPL. The GPL does not remove your copyright to your own code. It just grants the users the freedom to do with it as they wish within the GPL. Should Terciob decide tomorrow to replace LibCompress with a non gpl alternative, and fix the license. He is absolutely free to do so. Such a change wouldn't invalidate the licensure on the previous versions, but all other versions going forward would be non GPL in that case. Just because he uses GPL does not mean he does not own his code.

**Comment by JustusW** [comment]
You are free to refer to that car crash of a discussion any way you like. The facts are: At this moment in time Details violates the licensing terms of the GPL by not redistributing under the same license.

It continues to baffle me how folks keep on digging when told they're in a hole. All your anti free and open source sentiment does is damage the project. And it is anti free software, because you don't understand that free software doesn't mean the developer gets no money. The free refers to how you can access it and what you can do with it, not what and how you pay for it.

But I'm not wasting any more time explaining FOSS and its principles here. This is why I referred to wow addon development as a toxic waste dump. It attracts people that use FOS Software without understanding the fundamentals let alone having the intention to actually honor them. Dunno why. Don't care anymore. 

The only reason I haven't dumped the repo and uninstalled details is that Tercioo hasn't stated anything to me or in any discussion on the topic I've seen and I won't hold I'll informed and/or rude people in his community against him.

EoD for me, kindly don't continue mentioning me, because I sort of want to stay subscribed in case Tercioo does feel like commenting.

**Comment by ellimccale** [comment]
omg take your back-and-forth conversations elsewhere. None of this is
related to the posted issue. Tired of getting emails for this (and I'm
aware of the irony that my replying will generate another email).

**Comment by SpareSimian** [comment]
Completed? I use Ajour and it doesn't see this as a valid addon URL. I don't see release.json anywhere in the repo. 

(I've been using Skada for damage/thread/heal meters and was looking for a maintained alternative and Details was suggested.)

**Comment by JustusW** [comment]
It is indeed now on wago.io so that makes it compatible with WoWUp. Thank you, I'll remove my own mirror.

**Comment by SpareSimian** [comment]
Adding the metadata to the release on GitHub is still desirable so it can be directly updated from here.

**Comment by austinrr** [comment]
Looks like this issue is closed and to be unresolved by https://github.com/Tercioo/Details-Damage-Meter/issues/268 or https://github.com/Tercioo/Details-Damage-Meter/issues/434

If you, like me, desire a workaround now, I've created a repository that packages releases automatically every 2 hours that can be used by Instawow, Wowup or other similar utilities.

https://github.com/austinrr/details-mirror

**Comment by akanouras** [comment]
> It is already on wago. Your post is invalid

Assuming Hanlon's Razor applies, here's why their post is not invalid:

1. The addon is available on Curse and Wago
2. Open source addon downloaders cannot use Curse
3. Open source addon downloaders cannot use Wago without subjecting the user to the Wago ToS, which forces ad display and, by extension, behaviour tracking
4. Open source addon downloaders can also use Github directly, provided the repo follows a specific protocol
5. This repo does not follow that protocol, and so cannot be used directly by downloaders bound by 1. and 2.
