### ISSUE TITLE
[RU] Some text strings are missing font (squares instead letters)

### ISSUE THREAD

**Issue by kanodiry** [Tercioo/Details-Damage-Meter#477]
Vesrion
DETAILS! VERSION: WD 10662 RELEASE 3.4.1

Mostly this persists on drop down menus and affect cyrillic symbols.

![image](https://user-images.githubusercontent.com/62216589/226432447-72415917-7542-4761-aecc-46fc9be285f2.png)

**Comment by clancyby** [comment]
[Details.DF.Wrath.10.0.7.10737.148](https://github.com/Tercioo/Details-Damage-Meter/tree/Details.DF.Wrath.10.0.7.10737.148) (2023-03-27)
the problem is actual
![imgonline-com-ua-2to1-3coI5DxTrT5fUV](https://user-images.githubusercontent.com/61461975/228090995-5486ce91-7bc2-40da-888f-ca2e55f40a62.jpg)

**Comment by clancyby** [comment]
To fix the display of the Cyrillic alphabet (squares instead of letters), you need to create a Fonts folder in the _retail_ folder (_classic_ for classics, etc.) and upload this file there (the file is in the archive because github does not allow uploading it).
This is the same standard font for wow, but it supports Cyrillic on its servers, which for some reason use a font without Cyrillic.
[FRIZQT__.zip](https://github.com/Tercioo/Details-Damage-Meter/files/11134735/FRIZQT__.zip)

**Comment by kanodiry** [comment]
Honestly, I realized that the problem is in the font (no Cyrillic characters in the font), but I tried to put FRIZQT__.ttf in the Details! folder, instead of the game folder.
Thank you for help!
