### ISSUE TITLE
Can't set Title Bar to full transparency after last update. 

### ISSUE THREAD

**Issue by SteveC84** [Tercioo/Details-Damage-Meter#79]
I've always had my Title bar set for full transparency, and now after the last update I can't find a setting to adjust it. Is there a new way to do it after the overhaul to the autohide features you just updated?

**Comment by CyberXaz** [comment]
**How do I hide the title bar? [-window -titlebar -hide]** The title bar is a part of the window skin and there's many ways to customize it. You can adjust the transparency (setting it to zero to totally hide) at /de options > Window: Settings > Window Color > Adjust the Alpha slider. You may auto hide the buttons or disable them at Title Bar: General > Auto Hide Buttons. You may auto hide/show the title bar when the mouse is over the window by setting: Window: Automatization > Enable Mouse Interaction + Ignore Bars, set On Hover to '1' and No Interaction to '0'.

I have the same problem, followed the guide but, anytime I reload, enter an instance,... alpha slider is at 0 but I can see the titlebar.

**Comment by montstros1ty** [comment]
Yep, getting the same here too. I've got my damage meter portion embedded into my Chat Frame so that's usually hidden unless I tab into it, but the threat portion is a separate frame visible on screen, and the ugly black title bar which now shows. Adjusting the slider into 'Window Color' will remove it temporarily until I join a party, or change zones.

**Comment by Tercioo** [comment]
It's a known bug on latest version from June 27th.

------ Original Message ------

**Comment by Tercioo** [comment]
Fixed!
