### ISSUE TITLE
[Cata Classic] VCT 13000 RELEASE 4.4.0 LibOpenraid error

### ISSUE THREAD

**Issue by Road-block** [Tercioo/Details-Damage-Meter#825]
### **Before Start!**
**Make sure the bug also happen when Details! is the only addon enabled.**

**Game and Details! version**
Details.13000.160 (on curse) `VCT 13000 RELEASE 4.4.0` reported by /details version

**Describe the bug**
Happens on load.

**Lua Error**
```
2x Details/functions/slash.lua:3814: Cannot find a library instance of "LibOpenRaid-1.0".
[string "=[C]"]: in function `error'
[string "@Ace3/LibStub/LibStub.lua"]:23: in function `GetLibrary'
[string "@Details/functions/slash.lua"]:3814: in function `RegisterForOpenRaidNotes'
[string "@Details/startup.lua"]:98: in function `StartMeUp'
[string "@Details/core/parser.lua"]:6394: in function <Details/core/parser.lua:6393>

Locals:
(*temporary) = "Cannot find a library instance of "LibOpenRaid-1.0"."
```

**Screenshots**
Post images of the bug if necessary.

**Combat Log**
Include a link to a combatlog file if the error is about not detecting a skill, usable item or item proc.
The log can be as simple as hitting a mob with white damage and using the item/skill.

**Other Information**
If necessary, add more info here.

**Comment by Road-block** [comment]
Offending line needs changing to 
```lua
local openRaidLib = LibStub:GetLibrary("LibOpenRaid-1.0", true)
```
so load fails silently since the next line checks for instantiation of the library.

**Comment by Tercioo** [comment]
fixing


------ Original Message ------
From "Road-block" ***@***.******@***.***>>
To "Tercioo/Details-Damage-Meter" ***@***.******@***.***>>
Cc "Subscribed" ***@***.******@***.***>>
Date 07-Sep-24 5:18:36 PM
Subject Re: [Tercioo/Details-Damage-Meter] [Cata Classic] VCT 13000 RELEASE 4.4.0 LibOpenraid error (Issue #825)


Offending line needs changing to

local openRaidLib = LibStub:GetLibrary("LibOpenRaid-1.0", true)

so load fails silently since the next line checks for instantiation of the library.
